import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Fulsome CG International VFX Academy Thrissur | Best VFX Training Institute Kerala | 100% Job Placement",
  description: "India's #1 job-based VFX training academy in Thrissur, Kerala. Learn rotoscopy, compositing, motion graphics, Nuke, After Effects with AI integration. 95% placement rate, industry-expert trainers, live projects. Enroll in AVFX (9 months), RPVFX (6 months), RTVFX (3 months) courses. Career in Bollywood, Hollywood, OTT platforms awaits!",
  keywords: [
    "VFX training Thrissur",
    "best VFX academy Kerala",
    "VFX courses Thrissur Kerala",
    "VFX training institute near me",
    "rotoscopy training Thrissur",
    "paint prep VFX course",
    "Nuke compositing training Kerala",
    "After Effects course Thrissur",
    "motion graphics training Kerala",
    "video editing course Thrissur",
    "AI VFX training India",
    "job-based VFX training",
    "VFX placement assistance",
    "VFX internship Kerala",
    "visual effects academy Thrissur",
    "AVFX advanced VFX course",
    "RPVFX roto paint course",
    "RTVFX rotoscopy training",
    "Nuke training center Kerala",
    "After Effects institute Thrissur",
    "Premiere Pro training Kerala",
    "Mocha Pro course India",
    "Silhouette FX training Thrissur",
    "3D animation VFX course",
    "film VFX training Kerala",
    "digital art VFX academy",
    "VFX career courses India",
    "visual effects school Kerala",
    "animation VFX training Thrissur",
    "post production training Kerala",
    "Fulsome CG International",
    "VFX jobs Kerala Thrissur",
    "VFX training center Thrissur",
    "VFX artist course Kerala",
    "compositing artist training",
    "roto artist training Thrissur",
    "VFX online classes Kerala",
    "VFX offline training Thrissur",
    "best VFX institute South India",
    "VFX course fees Kerala",
    "VFX training duration Kerala",
    "Hollywood VFX training India",
    "Bollywood VFX course Thrissur",
    "OTT VFX training Kerala",
    "AI-powered VFX course",
    "Stable Diffusion VFX training",
    "Midjourney VFX course",
    "RunwayML training Kerala",
    "VFX career salary India",
    "VFX job opportunities Kerala",
  ] as Array<string>,
  authors: {
    name: "Fulsome CG International VFX Academy",
    url: "https://www.fulsomecg.in",
  },
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: "https://www.fulsomecg.in",
    title: "Fulsome CG International VFX Academy | Premier VFX Training in Thrissur",
    description: "India's first job-based VFX training centre with AI integration. Learn from industry experts and launch your VFX career.",
    siteName: "Fulsome CG International VFX Academy",
  },
  twitter: {
    card: "summary_large_image",
    title: "Fulsome CG International VFX Academy",
    description: "Transform your passion into a VFX career with industry-leading training in Thrissur, Kerala.",
  },
} as const;
